Kore\PageBundle\Entity\FrontpagePhoto:
    type: entity
    table: FrontpagePhoto
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        frontpage:
            targetEntity: Kore\PageBundle\Entity\Frontpage
            inversedBy: photos
    fields:
        path:
            type: string
            length: 300
            nullable: true
        file:
            type: string
            length: 300
            nullable: true
    lifecycleCallbacks: {  }