frontpagephoto_index:
    path:     /
    defaults: { _controller: "KorePageBundle:FrontpagePhoto:index" }
    methods:  GET

frontpagephoto_show:
    path:     /{id}/show
    defaults: { _controller: "KorePageBundle:FrontpagePhoto:show" }
    methods:  GET

frontpagephoto_new:
    path:     /new
    defaults: { _controller: "KorePageBundle:FrontpagePhoto:new" }
    methods:  [GET, POST]

frontpagephoto_edit:
    path:     /{id}/edit
    defaults: { _controller: "KorePageBundle:FrontpagePhoto:edit" }
    methods:  [GET, POST]

frontpagephoto_delete:
    path:     /{id}/delete
    defaults: { _controller: "KorePageBundle:FrontpagePhoto:delete" }
    methods:  DELETE
